<a href="https://colab.research.google.com/github/Krosumlabs/AI/blob/main/RAG_Appln_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import sys
sys.version

'3.12.13 (main, Mar  4 2026, 09:23:07) [GCC 11.4.0]'

In [2]:
print(sys.platform)

linux


In [3]:
import time
time.sleep(15)
print("OK")

OK


In [ ]:
'''
NLP
----
 |-> Text Processing - Clean the text(lowercase ; remove punctuation; removing stopwords)
 |-> Tokenization  - split sentence into words/token
 |-> Text Representation - Token ->Vector(numbers)
 |                         --------------------------// OneHotEncoding / BOW/TF-IDF
 |-> word2vector -->embedding
 |-> Modern NLP  //uses deep learning + transformer
 |    |->BERT GPT
 #----------------------------------------------------------------------
 # NLP is the foundation of GenAI

 NLP Terms
 ---------
 1. Corpus
 2. Documents
 3. Words
 import nltk
'''

In [4]:
! pip show nltk

Name: nltk
Version: 3.9.1
Summary: Natural Language Toolkit
Home-page: https://www.nltk.org/
Author: NLTK Team
Author-email: nltk.team@gmail.com
License: Apache License, Version 2.0
Location: /usr/local/lib/python3.12/dist-packages
Requires: click, joblib, regex, tqdm
Required-by: textblob


In [ ]:
# ! pip install nltk

In [5]:
# nltk
#   |->tokenize

from nltk.tokenize import word_tokenize

text = "i liked to read machine learning algorithm"

word_tokenize(text)

LookupError: 
**********************************************************************
  Resource punkt_tab not found.
  Please use the NLTK Downloader to obtain the resource:

  >>> import nltk
  >>> nltk.download('punkt_tab')
  
  For more information see: https://www.nltk.org/data.html

  Attempted to load tokenizers/punkt_tab/english/

  Searched in:
    - '/root/nltk_data'
    - '/usr/nltk_data'
    - '/usr/share/nltk_data'
    - '/usr/lib/nltk_data'
    - '/usr/share/nltk_data'
    - '/usr/local/share/nltk_data'
    - '/usr/lib/nltk_data'
    - '/usr/local/lib/nltk_data'
**********************************************************************


In [6]:
import nltk
nltk.download('punkt_tab')

[nltk_data] Downloading package punkt_tab to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt_tab.zip.


True

In [7]:
from nltk.tokenize import word_tokenize

text = "i liked to read machine learning algorithm"

word_tokenize(text)

['i', 'liked', 'to', 'read', 'machine', 'learning', 'algorithm']

In [8]:
corpus = '''hello welcome,to gen ai training
do activity ! to become nlp learner
all the gen ai llm models are built on
top of nlp'''

In [10]:
print(word_tokenize(corpus))

['hello', 'welcome', ',', 'to', 'gen', 'ai', 'training', 'do', 'activity', '!', 'to', 'become', 'nlp', 'learner', 'all', 'the', 'gen', 'ai', 'llm', 'models', 'are', 'built', 'on', 'top', 'of', 'nlp']


In [11]:
from nltk.tokenize import word_tokenize
from nltk.tokenize import sent_tokenize

print(sent_tokenize(corpus))


['hello welcome,to gen ai training\ndo activity !', 'to become nlp learner\nall the gen ai llm models are built on\ntop of nlp']


In [12]:
msg="hello vinay,how are you doing? ok. i am doing nlp activities's code ab'c data1.data2.#!/bin"

In [13]:
print(word_tokenize(msg))

['hello', 'vinay', ',', 'how', 'are', 'you', 'doing', '?', 'ok.', 'i', 'am', 'doing', 'nlp', 'activities', "'s", 'code', 'ab', "'", 'c', 'data1.data2.', '#', '!', '/bin']


In [14]:
from nltk.tokenize import word_tokenize
from nltk.tokenize import sent_tokenize
from nltk.tokenize import wordpunct_tokenize
print(wordpunct_tokenize(msg))

['hello', 'vinay', ',', 'how', 'are', 'you', 'doing', '?', 'ok', '.', 'i', 'am', 'doing', 'nlp', 'activities', "'", 's', 'code', 'ab', "'", 'c', 'data1', '.', 'data2', '.#!/', 'bin']


In [15]:
# learning --->[101010] -- [101001]
# ========
#  stemming - reduce the root word
# learning --> learn -->[1010]
# --------     =====    ------

from nltk.stem import PorterStemmer
obj = PorterStemmer()
obj.stem('learning')

'learn'

In [16]:
obj.stem("eating")

'eat'

In [17]:
obj.stem("history")

'histori'

In [18]:
obj.stem("congratulations")

'congratul'

In [19]:
from nltk.stem import RegexpStemmer
reg_obj = RegexpStemmer("ing$|s$|e$|y$") # user speficic
reg_obj.stem('eating')

'eat'

In [20]:
reg_obj.stem('asfsfsfsfsdsfsdfsdfsding')

'asfsfsfsfsdsfsdfsdfsd'

In [ ]:
# Lemmatization - lemma
# reducing root word - based on POS = v,av...

In [21]:
from nltk.stem import WordNetLemmatizer
obj = WordNetLemmatizer()
obj.lemmatize('eating')

LookupError: 
**********************************************************************
  Resource wordnet not found.
  Please use the NLTK Downloader to obtain the resource:

  >>> import nltk
  >>> nltk.download('wordnet')
  
  For more information see: https://www.nltk.org/data.html

  Attempted to load corpora/wordnet

  Searched in:
    - '/root/nltk_data'
    - '/usr/nltk_data'
    - '/usr/share/nltk_data'
    - '/usr/lib/nltk_data'
    - '/usr/share/nltk_data'
    - '/usr/local/share/nltk_data'
    - '/usr/lib/nltk_data'
    - '/usr/local/lib/nltk_data'
**********************************************************************


In [23]:
import nltk
nltk.download('wordnet')

[nltk_data] Downloading package wordnet to /root/nltk_data...


True

In [24]:
from nltk.stem import WordNetLemmatizer
obj = WordNetLemmatizer()
obj.lemmatize('eating')

'eating'

In [25]:
from nltk.stem import WordNetLemmatizer
obj = WordNetLemmatizer()
obj.lemmatize('eating',pos='v')

'eat'

In [26]:
obj.lemmatize('history',pos='v')

'history'

In [27]:
# Apply stop words - reserved words
#-------------------------
# the home food is good // ---> 5 words
# -------------------- # the is - removed - the is are stop words
#    home food good  // ------> 3 word

# Stopwords - do not carrying significant meaning
# --------- - reduce Noise - reduce vocabulary size
#                              -------------------------//imporve processing efficiency
#
from nltk.corpus import stopwords
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.


True

In [32]:
#stopwords.words('english')
#stopwords.words('french')
#stopwords.words('arabic')


In [33]:
Given_List = ['words','eats','eatern','writing','writes','programming','program','history','finally','finalized']
obj = PorterStemmer()
for var in Given_List:
  print(f'{var} -->{obj.stem(var)}')

words -->word
eats -->eat
eatern -->eatern
writing -->write
writes -->write
programming -->program
program -->program
history -->histori
finally -->final
finalized -->final


In [34]:
obj = WordNetLemmatizer()
for var in Given_List:
  print(f"{var} -->{obj.lemmatize(var,pos='v')}")

words -->word
eats -->eat
eatern -->eatern
writing -->write
writes -->write
programming -->program
program -->program
history -->history
finally -->finally
finalized -->finalize


In [44]:
msg="This is an EXAMPLE displaying off list of or collection of stop words filters"

In [45]:
words = word_tokenize(msg)
print(len(words))

14


In [46]:
filter_words = [var.lower() for var in words if var.lower() not in stopwords.words('english')]
print(filter_words)

['example', 'displaying', 'list', 'collection', 'stop', 'words', 'filters']


In [47]:
print(len(filter_words))

7


In [48]:
## Task
#----------
# Corpus <== take your own paragraph
#    |--> PorterStemmer / WordNetLemmatizer
#    |--> Apply Stopwords
#    |--> Filter remaining words
# --------
corpus ='''
Vikram Ambalal Sarabhai (12 August 1919 – 30 December 1971) was an Indian physicist and astronomer who initiated space research and
helped to develop nuclear power in India.
Often regarded as the "Father of Indian space program",[2] Sarabhai was honored with Padma Bhushan in 1966 and
the Padma Vibhushan (posthumously) in 1972.
'''

In [52]:
from nltk.stem import PorterStemmer
from nltk.corpus import stopwords

stemm_obj = PorterStemmer()
docs = nltk.sent_tokenize(corpus)

for var in range(len(docs)):
  words = nltk.word_tokenize(docs[var])
  words = [stemm_obj.stem(word) for word in words if word not in stopwords.words('english')]
  docs[var] = ' '.join(words)

print(docs)

['vikram ambal sarabhai ( 12 august 1919 – 30 decemb 1971 ) indian physicist astronom initi space research help develop nuclear power india .', "often regard `` father indian space program '' , [ 2 ] sarabhai honor padma bhushan 1966 padma vibhushan ( posthum ) 1972 ."]


In [55]:
from nltk.stem import WordNetLemmatizer
from nltk.corpus import stopwords

lemma_obj = WordNetLemmatizer()
docs = nltk.sent_tokenize(corpus)

for var in range(len(docs)):
  words = nltk.word_tokenize(docs[var])
  words = [lemma_obj.lemmatize(word,pos='v') for word in words if word not in stopwords.words('english')]
  docs[var] = ' '.join(words)

print(docs)

['Vikram Ambalal Sarabhai ( 12 August 1919 – 30 December 1971 ) Indian physicist astronomer initiate space research help develop nuclear power India .', "Often regard `` Father Indian space program '' , [ 2 ] Sarabhai honor Padma Bhushan 1966 Padma Vibhushan ( posthumously ) 1972 ."]


In [ ]:
# token/word -> Convert to Vector
# -----------------------------------
# 1. One-Hot encoding
'''
words = ['home','food','good']
home -->   1 0 0  -> [1,0,0]
food -->   0 1 0  -> [0,1,0]
good -->   0 0 1  -> [0,0,1]

ngram
-----
 |-> Contiguous sequence of n items from given corpus

 ['home','food','good'] <= 3 words

 n = 1

words = ['home','food','good']
home -->   1 0 0  -> [1,0,0]
food -->   0 1 0  -> [0,1,0]
good -->   0 0 1  -> [0,0,1]

 n = 2
 home food ----> 1 0 [1,0]
 food good ----> 0 1 [0,1]

 n = 3
 home food good
 --------------->  1   [1]
 --------------->  0   [0]
'''

In [56]:
from nltk.util import ngrams

In [57]:
data = 'likes read nlp applications'
word_tokenize(data)

['likes', 'read', 'nlp', 'applications']

In [58]:
# ngrams(token,Count) ->Generator
ngrams(word_tokenize(data),1)

<generator object ngrams at 0x7bf56fb89f40>

In [59]:
list(ngrams(word_tokenize(data),1))

[('likes',), ('read',), ('nlp',), ('applications',)]

In [60]:
list(ngrams(word_tokenize(data),2))

[('likes', 'read'), ('read', 'nlp'), ('nlp', 'applications')]

In [61]:
list(ngrams(word_tokenize(data),3))

[('likes', 'read', 'nlp'), ('read', 'nlp', 'applications')]

In [ ]:
'''
ML is a sub of set of ____AI___

maths  - 0.2
science - 10.2
AI ------- 99.99 <==== AI
data - 45.0
'''

In [62]:
list(ngrams(word_tokenize(data),4))

[('likes', 'read', 'nlp', 'applications')]

In [66]:
import numpy as np
from sklearn.preprocessing import OneHotEncoder

data = ['home','food','good']
data = np.array(data).reshape(-1,1) # 2D
encoder_obj = OneHotEncoder(sparse_output=False)
one_hot_vector = encoder_obj.fit_transform(data)
print(encoder_obj.categories_)
print('')
print(one_hot_vector)

[array(['food', 'good', 'home'], dtype='<U4')]

[[0. 0. 1.]
 [1. 0. 0.]
 [0. 1. 0.]]


In [68]:
data = ['indian','physicist','astronom', 'initi','space','research','help','develop','nuclear','power','india']
data = np.array(data).reshape(-1,1)
encoder_obj = OneHotEncoder(sparse_output=False)
one_hot_vector = encoder_obj.fit_transform(data)
print(encoder_obj.categories_)
print('')
print(one_hot_vector)

[array(['astronom', 'develop', 'help', 'india', 'indian', 'initi',
       'nuclear', 'physicist', 'power', 'research', 'space'], dtype='<U9')]

[[0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]]


In [73]:
# Bag of Words - BOW
# ------------------------ + frequency
from sklearn.feature_extraction.text import CountVectorizer
docs = ['i likes nlp and i likes python','python web python and python course']

In [74]:
cv = CountVectorizer()
bow = cv.fit_transform(docs)
print(cv.get_feature_names_out())
print(bow.toarray())

['and' 'course' 'likes' 'nlp' 'python' 'web']
[[1 0 2 1 1 0]
 [1 1 0 0 3 1]]


In [72]:
# Vector -> numerical array [1,0,0,2]
#
# Embedding - type of vector
#             --------------- //semantics

# "python" -> [0.2,0.8,-1.2] <----- snake
# "dog" -->   [0.25,0.85,-1.44]
#
# Vs
#
# "python" --> [1.5,1.6,-1.6] <---- programming python
# "java"-----> [1.4,1.7,-1.7]

# Emebeddings place similar things closer in vector space
#
# Sematic search
#
# 384 - vectors
# 768 - vectors
# 1024 ..
# 1536 ...
#-------------------------------------------------------
# Langchain
#  - Framework
#  - GenAI Application
#  - chain,prompt,memory,agent ..
#  - ------
#     |-> [DataLoading]-->[Chunk]-->[Embedding]--->[Stores to VectorDB]
#        -------------- ----------- --------------------------------------
#                   ----->------->---------->---------

# Langchain LangGraph  LangSmith
#  |           |       =========
# DevTool   DevTool       |->Monitoring - UI
#              |->Agent

Text Loader
Chunk
Embedding - model

################
'''
1. Data Loading from various sources
                              |-> file,database,web,wikipedia,URL,JSON..... //loader classes

2. Split data into multiple chunks

3. Using Embedding model ->Chunks ->Vectors

4. Stores to VectorDB (FAISS,Oracle23AI,Chroma)

5. Test: Similarity Search
---------------------------------//

6. RAG
7. prompt - rules
8. prompt chain - connect with llm
9. llm ->response
10. User Interface




docs: python is a general purpose programming
  |
  chunk1 - | python is a | -----> [embeddings] --------> [DB]
  chunk2 - | is a general purpose| -->[embeddings] ----> [DB]      <--
  chunk3 - | purpose programming| -->[embedding] ----------[DB]


Ollama
=========
1. Download ollama setup file and install it.
2. Go to commandline
3. type following commands
    3.1 -> ollama list
    3.2 -> ollama pull <modelName> (ex: ollama pull gemma2:2b)
    3.3 -> ollama list
    3.4 -> ollama run <modelName> (Ex: ollama run gemma2:2b)
           ======================
4. Ctrl+D - Exit from Ollama shell

|
|
Using langchain
================
from langchain_ollama import OllamaLLM
llm_obj = OllamaLLM(model='gemma2:2b')
response = llm_obj.invoke('What is GenAI?')
print(type(response),len(response))

'''

In [75]:
!curl -fsSL https://ollama.com/install.sh | sh

>>> Installing ollama to /usr/local
ERROR: This version requires zstd for extraction. Please install zstd and try again:
  - Debian/Ubuntu: sudo apt-get install zstd
  - RHEL/CentOS/Fedora: sudo dnf install zstd
  - Arch: sudo pacman -S zstd


In [ ]:
! ollama serve & # start Ollama server
! ollama pull gemma2:2b # Pull a model
! ollama run gemma2:2b # run inference
! ollama run gemma2:2b "What is genAI?"

In [77]:
# Load the document
#
# langchain community
#               |->document_loaders
#                             |->TextLoader |->PDFLoader | ExcelLoader ....
#
# Using document loader class - get the document
#                                      ========== metadata + actualdata //dict
#
#          metadata={'source':<>},page_content='Actual data' //Response
! pip install -r requirements.txt

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 52.0/52.0 kB 3.8 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.5/2.5 MB 36.7 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 21.6/21.6 MB 59.6 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 333.7/333.7 kB 24.7 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 23.8/23.8 MB 65.3 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 137.5/137.5 kB 11.8 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 65.0/65.0 kB 5.7 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 9.1/9.1 MB 97.5 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.0/1.0 MB 47.5 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 278.2/278.2 kB 16.5 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.0/2.0 MB 42.6 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 17.2/17.2 MB 22.9 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 72.1/72.1 

In [1]:
from langchain_community.document_loaders import TextLoader
print(TextLoader)

<class 'langchain_community.document_loaders.text.TextLoader'>


In [3]:
# loader_obj = TextLoader('inputFile') # Constructor
# |
# loader_obj.load() //method  --->documents{metadata+actual_data}

loader_obj = TextLoader('my_docs.txt')
loader_obj.load()

[Document(metadata={'source': 'my_docs.txt'}, page_content="LangChain is a framework for developing applications powered by large language models (LLMs).\n\nLangChain simplifies every stage of the LLM application lifecycle:\n\nDevelopment: Build your applications using LangChain's open-source components and third-party integrations. Use LangGraph to build stateful agents with first-class streaming and human-in-the-loop support.\nProductionization: Use LangSmith to inspect, monitor and evaluate your applications, so that you can continuously optimize and deploy with confidence.\nDeployment: Turn your LangGraph applications into production-ready APIs and Assistants with LangGraph Platform.\n\nfactorial value 5! is 120")]

In [4]:
from langchain_community.document_loaders import PyPDFLoader

In [5]:
from langchain_community.document_loaders import TextLoader
loader_obj = TextLoader('my_docs.txt')
Text_docs = loader_obj.load()

from langchain_community.document_loaders import PyPDFLoader
loader_obj = PyPDFLoader('attention.pdf')
pdf_docs = loader_obj.load()

In [6]:
print(type(Text_docs),len(Text_docs))

<class 'list'> 1


In [7]:
print(type(pdf_docs),len(pdf_docs))

<class 'list'> 15


In [12]:
#pdf_docs[-1]

In [13]:
from langchain_community.document_loaders import WikipediaLoader

# WikipediaLoader(query='Question') ->Loader_obj.load() ->data
# WikipediaLoader(query='Question',load_max_docs=<count>) ->Loader_obj.load() ->data


loader_obj = WikipediaLoader(query='What is Langchain?')
loader_obj.load()

ImportError: Could not import wikipedia python package. Please install it with `pip install wikipedia`.

In [14]:
! pip install wikipedia

  Preparing metadata (setup.py) ... done
  Created wheel for wikipedia: filename=wikipedia-1.4.0-py3-none-any.whl size=11678 sha256=3ade494b8f32b47ab44e337ba5ec02314e0a767023ca9e3454ca9a74ccdf09ac
  Stored in directory: /root/.cache/pip/wheels/63/47/7c/a9688349aa74d228ce0a9023229c6c0ac52ca2a40fe87679b8
Successfully built wikipedia


In [16]:
from langchain_community.document_loaders import WikipediaLoader

# WikipediaLoader(query='Question') ->Loader_obj.load() ->data
# WikipediaLoader(query='Question',load_max_docs=<count>) ->Loader_obj.load() ->data


loader_obj = WikipediaLoader(query='What is Langchain?',load_max_docs=2)
loader_obj.load()

[Document(metadata={'title': 'Model Context Protocol', 'summary': 'The Model Context Protocol (MCP) is an open standard and open-source framework introduced by Anthropic in November 2024 to standardize the way artificial intelligence (AI) systems like large language models (LLMs) integrate and share data with external tools, systems, and data sources. MCP provides a universal interface for reading files, executing functions, and handling contextual prompts. Following its announcement, the protocol was adopted by major AI providers, including OpenAI and Google DeepMind.\n\n', 'source': 'https://en.wikipedia.org/wiki/Model_Context_Protocol'}, page_content='The Model Context Protocol (MCP) is an open standard and open-source framework introduced by Anthropic in November 2024 to standardize the way artificial intelligence (AI) systems like large language models (LLMs) integrate and share data with external tools, systems, and data sources. MCP provides a universal interface for reading fil

In [19]:
# WebBaseLoader
from langchain_community.document_loaders import WebBaseLoader
loader_obj = WebBaseLoader(web_path='https://www.google.com')
loader_obj.load()

[Document(metadata={'source': 'https://www.google.com', 'title': 'Google', 'description': "Search the world's information, including webpages, images, videos and more. Google has many special features to help you find exactly what you're looking for.", 'language': 'en'}, page_content='GoogleGmailImagesSign in\xa0Advanced searchAdvertisingBusiness SolutionsAbout Google© 2026 - Privacy - TermsGoogle apps')]

In [20]:
loader_obj = WebBaseLoader(web_paths=['https://www.google.com','https://www.python.org'])
loader_obj.load()

[Document(metadata={'source': 'https://www.google.com', 'title': 'Google', 'description': "Search the world's information, including webpages, images, videos and more. Google has many special features to help you find exactly what you're looking for.", 'language': 'en'}, page_content='GoogleGmailImagesSign in\xa0Advanced searchAdvertisingBusiness SolutionsAbout Google© 2026 - Privacy - TermsGoogle apps'),
 Document(metadata={'source': 'https://www.python.org', 'title': 'Welcome to Python.org', 'description': 'The official home of the Python Programming Language', 'language': 'en'}, page_content='\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\nWelcome to Python.org\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\nNotice: This page displays a fallback because interactive scripts did not run. Possible causes include disabled JavaScript or failure to load scripts or stylesheets.\n\n\n\n\n\nSkip to content\n\n\n▼ Close\n                \n\n\nPython\n\n\nPSF\n\n\nDocs\n\n\nPyPI\n\n\nJobs\n

In [21]:
!pip show requests

Name: requests
Version: 2.33.0
Summary: Python HTTP for Humans.
Home-page: 
Author: 
Author-email: Kenneth Reitz <me@kennethreitz.org>
License: Apache-2.0
Location: /usr/local/lib/python3.12/dist-packages
Requires: certifi, charset_normalizer, idna, urllib3
Required-by: bigframes, blosc2, CacheControl, community, datasets, diffusers, earthengine-api, fastai, folium, gcsfs, gdown, geocoder, google-adk, google-api-core, google-cloud-bigquery, google-cloud-storage, google-colab, google-genai, googledrivedownloader, jupyter_kernel_gateway, kaggle, kagglehub, kagglesdk, keyrings.google-artifactregistry-auth, kubernetes, langchain-classic, langchain-community, langsmith, libpysal, moviepy, music21, opentelemetry-exporter-otlp-proto-http, opentelemetry-resourcedetector-gcp, pandas-datareader, panel, pooch, pyiceberg, pysal, quantecon, requests-oauthlib, requests-toolbelt, spacy, spanner-graph-notebook, Sphinx, streamlit, tensorflow, tensorflow-datasets, tiktoken, torchdata, tsfresh, tweepy, w

In [22]:
!pip show bs4

Name: bs4
Version: 0.0.2
Summary: Dummy package for Beautiful Soup (beautifulsoup4)
Home-page: 
Author: 
Author-email: Leonard Richardson <leonardr@segfault.org>
License: MIT License
Location: /usr/local/lib/python3.12/dist-packages
Requires: beautifulsoup4
Required-by: 


In [23]:
import requests
r = requests.get('https://www.google.com')
r.headers

{'Date': 'Mon, 30 Mar 2026 11:06:28 GMT', 'Expires': '-1', 'Cache-Control': 'private, max-age=0', 'Content-Type': 'text/html; charset=ISO-8859-1', 'Content-Security-Policy-Report-Only': "object-src 'none';base-uri 'self';script-src 'nonce-iambAjtIod6Y6nLpTtWRCA' 'strict-dynamic' 'report-sample' 'unsafe-eval' 'unsafe-inline' https: http:;report-uri https://csp.withgoogle.com/csp/gws/other-hp", 'Reporting-Endpoints': 'default="//www.google.com/httpservice/retry/jserror?ei=NFnKadnXMvGXwbkP4pjWiQ8&cad=crash&error=Page%20Crash&jsel=1&bver=2410&dpf=WdOTFTXbSEfM_VAjA2yzNlj9Sm5SIUG8ZtAYAFUTjr8"', 'Accept-CH': 'Sec-CH-Prefers-Color-Scheme', 'P3P': 'CP="This is not a P3P policy! See g.co/p3phelp for more info."', 'Content-Encoding': 'gzip', 'Server': 'gws', 'X-XSS-Protection': '0', 'X-Frame-Options': 'SAMEORIGIN', 'Set-Cookie': '__Secure-STRP=AEEP7gKH1WGIESNZ_kFKtUJMJ-bHahNU-htRC-kNw7twWjo8bUKMEid_NQkR4hVF6TzCXnp1JhhqqE4uK8-I51SwS-NU2Uifi102; expires=Mon, 30-Mar-2026 11:11:28 GMT; path=/; domain

In [24]:
import requests
r = requests.get('https://www.google.com')
r.text

'<!doctype html><html itemscope="" itemtype="http://schema.org/WebPage" lang="en"><head><meta content="Search the world\'s information, including webpages, images, videos and more. Google has many special features to help you find exactly what you\'re looking for." name="description"><meta content="noodp, " name="robots"><meta content="text/html; charset=UTF-8" http-equiv="Content-Type"><meta content="/images/branding/googleg/1x/googleg_standard_color_128dp.png" itemprop="image"><title>Google</title><script nonce="jZO8DD8oaTCrKFCs_el0Xw">(function(){var _g={kEI:\'VVnKaYX3HOiMwbkPg9CDgA0\',kEXPI:\'0,1304203,2935842,48791,46127,344796,226411,1,44064,5262502,36811390,25228681,123988,28395,65164,39774,74608,23968,37800,28333,79315,7707,7,30734,1,3,2647,26230,2863,1,22727,30421,15919,20673,5,11882,6436,9743,2646,24246,15888,1,2,1515,3355,196,571,5243,2,3418,16888,2,873,2,23,2207,5108,3007,16,780,4074,4,5393,27152,5337,310,535,2046,2,11,2,1560,3,5204,1,13,1732,2,1746,4,4878,5773,4542,4,2243,

In [25]:
import bs4
soup_obj = bs4.BeautifulSoup(r.text)
soup_obj.title

<title>Google</title>

In [26]:
soup_obj.title.string

'Google'

In [27]:
soup_obj.find('title')

<title>Google</title>

In [28]:
soup_obj.find('p')

<p style="font-size:8pt;color:#636363">© 2026 - <a href="/intl/en/policies/privacy/">Privacy</a> - <a href="/intl/en/policies/terms/">Terms</a></p>

In [29]:
soup_obj.find_all('p')

[<p style="font-size:8pt;color:#636363">© 2026 - <a href="/intl/en/policies/privacy/">Privacy</a> - <a href="/intl/en/policies/terms/">Terms</a></p>]

In [33]:
'''
To Extract specific tag from webpage
|
import bs4
|
bs_kwargs = bs4.SoupStrainer(class_ = ('<inputTag1>,<inputTag2>,<inputTag3>,....<inputTagN>'))
|
WebBaseLoader(web_path=URL,bs_kwargs=dict())
'''
URL='https://www.python.org'
loader = WebBaseLoader(web_path=(URL),bs_kwargs=dict(parse_only=bs4.SoupStrainer(class_=("navigation menu"))))
loader.load()

[Document(metadata={'source': 'https://www.python.org'}, page_content="\n\nA A\n\nSmaller\nLarger\nReset\n\n\n\n\nSocialize\n\nLinkedIn\nMastodon\nChat on IRC\nTwitter\n\n\n\n\nAbout\n\nApplications\nQuotes\nGetting Started\nHelp\nPython Brochure\n\n\n\nDownloads\n\nAll releases\nSource code\nWindows\nmacOS\nAndroid\nOther Platforms\nLicense\nAlternative Implementations\n\n\n\nDocumentation\n\nDocs\nAudio/Visual Talks\nBeginner's Guide\nFAQ\nNon-English Docs\nPEP Index\nPython Books\nPython Essays\n\n\n\nCommunity\n\nDiversity\nMailing Lists\nIRC\nForums\nPSF Annual Impact Report\nPython Conferences\nSpecial Interest Groups\nPython Logo\nPython Wiki\nCode of Conduct\nCommunity Awards\nGet Involved\nShared Stories\n\n\n\nSuccess Stories\n\nArts\nBusiness\nEducation\nEngineering\nGovernment\nScientific\nSoftware Development\n\n\n\nNews\n\nPython News\nPSF Newsletter\nPSF News\nPyCon US News\nNews from the Community\n\n\n\nEvents\n\nPython Events\nUser Group Events\nPython Events Archive\

In [ ]:
loader_obj = WebBaseLoader(web_path='https://www.python.org')
loader_obj.load()
## Vs
URL='https://www.python.org'
loader = WebBaseLoader(web_path=(URL),bs_kwargs=dict(parse_only=bs4.SoupStrainer(class_=("navigation menu"))))
loader.load()

In [ ]:
# Data Loader
'''
|
After loading data from <Source>
|
Split data into multiple chunks
---- --------------------------
Chunking - breaking a large documents into smaller pieces(chunks)
--------
chunking
overlapping - adding/appending small portion of previous chunk into the next chunk
Chunk size = 100 words
overlap = 20 words

Chunk1 - words 1 - 100
Chunk2 - words 81 - 180
Chunk3 - words 161 - 260
|
Each Chunk ->Embedding (vectors)
|
Stored in Vector DB
|
When user asks a question:
    -> Relevant Chunks are retrieved --->sent to llm as context

200-500
10-20% overlap

python is a general programming language its supports various modules to use ml and genai

python is a gen
eral progra
ming langu
   ---------------- Vs
python is a gen
general programming
programming language its

1. Character Text Splitter
2. RecurisiveCharater TextSplitter <====
3. HTML Splitter - tag <h1>...</h1>
4. JSON Splitter
'''

In [34]:
# Step - 1
# ----------
from langchain_community.document_loaders import TextLoader
loader = TextLoader('my_docs.txt')
docs = loader.load()

# Step - 2
# -------------
from langchain_text_splitters import CharacterTextSplitter
CharacterTextSplitter(chunk_size=100,chunk_overlap=20)

In [35]:
obj = CharacterTextSplitter(chunk_size=100,chunk_overlap=20)
obj.split_documents(docs)

[Document(metadata={'source': 'my_docs.txt'}, page_content='LangChain is a framework for developing applications powered by large language models (LLMs).'),
 Document(metadata={'source': 'my_docs.txt'}, page_content='LangChain simplifies every stage of the LLM application lifecycle:'),
 Document(metadata={'source': 'my_docs.txt'}, page_content="Development: Build your applications using LangChain's open-source components and third-party integrations. Use LangGraph to build stateful agents with first-class streaming and human-in-the-loop support.\nProductionization: Use LangSmith to inspect, monitor and evaluate your applications, so that you can continuously optimize and deploy with confidence.\nDeployment: Turn your LangGraph applications into production-ready APIs and Assistants with LangGraph Platform."),
 Document(metadata={'source': 'my_docs.txt'}, page_content='factorial value 5! is 120')]

In [36]:
html_str = '''
<html>
<body>
<div>
<h1>msg1</h1>
<p> Some sample data</p>
<div>
<h2>main section</h2>
<p> About home</p>
<h3> dev section</h3>
<p> Total no.of counts</p>
</div>
<br>
<p>outer text</p>
</div>
</body>
</html>'''

In [38]:
from langchain_text_splitters import HTMLHeaderTextSplitter
#help(HTMLHeaderTextSplitter)
HTMLHeaderTextSplitter([('h2','Header 2')]).split_text(html_str)

[Document(metadata={}, page_content='msg1  \nSome sample data'),
 Document(metadata={'Header 2': 'main section'}, page_content='main section'),
 Document(metadata={}, page_content='About home  \ndev section  \nTotal no.of counts  \nouter text')]

In [39]:
L=[('h1','Header 1'),('h2','Header 2'),('h3','Header 3')]
HTMLHeaderTextSplitter(L).split_text(html_str)

[Document(metadata={'Header 1': 'msg1'}, page_content='msg1'),
 Document(metadata={'Header 1': 'msg1'}, page_content='Some sample data'),
 Document(metadata={'Header 1': 'msg1', 'Header 2': 'main section'}, page_content='main section'),
 Document(metadata={'Header 1': 'msg1', 'Header 2': 'main section'}, page_content='About home'),
 Document(metadata={'Header 1': 'msg1', 'Header 2': 'main section', 'Header 3': 'dev section'}, page_content='dev section'),
 Document(metadata={'Header 1': 'msg1'}, page_content='Total no.of counts  \nouter text')]

In [40]:
splitted_data = HTMLHeaderTextSplitter(L).split_text_from_url('https://www.python.org')
len(splitted_data)

27

In [42]:
splitted_data

[Document(metadata={}, page_content='end #touchnav-wrapper  \nSister Site Links Header elements end #content .content-wrapper Footer and social media list  \nThis page displays a fallback because interactive scripts did not run. Possible causes include disabled JavaScript or failure to load scripts or stylesheets.  \nNotice:  \nSkip to content  \nClose  \n▼  \nPython  \nPSF  \nDocs  \nPyPI  \nJobs  \nCommunity  \nThe Python Network  \n▲  \nend .container  \nend options-bar  \nDonate  \nMenu  \n≡  \nSearch This Site  \nGO  \nA  \nA  \nSmaller  \nLarger  \nReset  \nSocialize  \nLinkedIn  \nMastodon  \nChat on IRC  \nTwitter  \nAbout  \nApplications  \nQuotes  \nGetting Started  \nHelp  \nPython Brochure  \nDownloads  \nAll releases  \nSource code  \nWindows  \nmacOS  \nAndroid  \nOther Platforms  \nLicense  \nAlternative Implementations  \nDocumentation  \nDocs  \nAudio/Visual Talks  \nBeginner\'s Guide  \nFAQ  \nNon-English Docs  \nPEP Index  \nPython Books  \nPython Essays  \nCommunity

In [ ]:
################################ End of Day1 ####################